DROP TABLE ANDESE_BASKETS;
DROP TABLE ANDESE_CATCHES;
DROP TABLE ANDESE_LV1_OBSERVATIONS;
DROP TABLE ANDESE_MISSIONS;
DROP TABLE ANDESE_SETS;
DROP TABLE ANDESE_SPECIMENS;

Create table ANDESE_BASKETS as select * from ESE_BASKETS where 1=2 ;
Create table ANDESE_CATCHES as select * from ESE_CATCHES where 1=2 ;
Create table ANDESE_LV1_OBSERVATIONS as select * from ESE_LV1_OBSERVATIONS where 1=2 ;
Create table ANDESE_MISSIONS as select * from ESE_MISSIONS where 1=2 ;
Create table ANDESE_SETS as select * from ESE_SETS where 1=2 ;
Create table ANDESE_SPECIMENS as select * from ESE_SPECIMENS where 1=2 ;